// Generated by CoffeeScript 1.8.0
var kebabulate;

kebabulate = function(camelString) {
  return camelString.replace(/([A-Z])/g, function($1) {
    return "-" + ($1.toLowerCase());
  });
};

module.exports = function(options) {
  return function(teacup) {
    teacup.renderAttrWithoutKebabulate = teacup.renderAttr;
    return teacup.renderAttr = function(name, value) {
      return teacup.renderAttrWithoutKebabulate(kebabulate(name), value);
    };
  };
};
